### ISSUE TITLE
Which robot will be used in the real phase?

### ISSUE THREAD

**Issue by WSPeng** [StanfordVL/GibsonSim2RealChallenge#4]
Hi, will the locobot be used in the real world phase? and which camera will be used? D435？
Thank you!

**Comment by ChengshuLi** [comment]
Thank you for your question.

The answer is yes. The README has been fixed in 04e7335a2cbd2e06444c141f9284b365da3382ee.
Robot spec: https://www.trossenrobotics.com/locobot-pyrobot-ros-rover.aspx
Camera spec: https://www.intelrealsense.com/depth-camera-d435/

Please feel free to re-open the issue if you have any further questions.

**Comment by fxia22** [comment]
The details of our parameters can be found [here](https://github.com/StanfordVL/GibsonSim2RealChallenge/blob/master/Parameters.md).
