### ISSUE TITLE
The camera tile angle of lobot is adjustable or not?

### ISSUE THREAD

**Issue by WSPeng** [StanfordVL/GibsonSim2RealChallenge#5]
Hi, the urdf file of locobot specified that the camera is horizontal. Maybe making it tilt towards gound is better (more useful information). I checked that there is a mechanism for adjusting the camera tilt angle on the locobot. May I ask if it adjustable in the real world phase?
Thank you

**Comment by fxia22** [comment]
Hi @WSPeng, we choose to tilt down the camera to 20 degrees, so that we provide a standardized test environment for participants. In experiments, we find tilting down 20 degrees strikes a balance between seeing enough context and avoiding close obstacles. The details of our parameters can be found [here](https://github.com/StanfordVL/GibsonSim2RealChallenge/blob/master/Parameters.md). It will not be adjustable in real world phase. 

The `head_tilt_joint` in urdf should be the following:

```xml
    <joint name="head_tilt_joint" type="fixed">
        <origin rpy="0 0.3490658503988659 0" xyz="0 0 0.05"/>
        <parent link="head_pan_link"/>
        <child link="head_tilt_link"/>
        <axis xyz="0 1 0"/>
        <limit effort="1" lower="-1.57" upper="1.57" velocity="1"/>
    </joint>
```

This has been updated in the latest `gibson_challeng_data.tar.gz`

**Comment by WSPeng** [comment]
Cool, the reason for this issue is that the camera can't see the coffee table and sofa when the Locobot is too close to them.
