### ISSUE TITLE
About the 72 high quality scenes (107 were given)

### ISSUE THREAD

**Issue by WSPeng** [StanfordVL/GibsonSim2RealChallenge#8]
Hi, I got 107 scenes from the Gibson challenge dataset whose name ranging from "Adrain" to "Woonsocket". As stated on the website, 72 of them are good quality and recommended. May I ask the list of the 72 scenes?

**Comment by fxia22** [comment]
You can safely include any or all of the 107 scenes in training as we expanded the high-quality scenes from 72 to 106 + Castro. We recommend starting with training in Castro only because that is most similar to the test scenes on which we will be doing the evaluations. After that you can include more scenes to train more generalizable policies.

**Comment by WSPeng** [comment]
ok, thanks
